# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlEqUCvNBINOyhEm8Z8JcZOo3DKXcJYJ
"""

import streamlit as st
import random
import numpy as np
import matplotlib.pyplot as plt
from colorsys import hsv_to_rgb

# -------------------------------
# 🎨 1. Palette generator
# -------------------------------
def generate_palette(style="Minimal", n_colors=6, seed=None):
    """Generate pastel or vivid color palettes depending on the selected style."""
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    base_hue = random.random()
    palette = []
    for _ in range(n_colors):
        h = (base_hue + random.uniform(-0.15, 0.15)) % 1.0
        if style == "Minimal":
            s = random.uniform(0.25, 0.45)
            v = random.uniform(0.85, 0.95)
        elif style == "Vivid":
            s = random.uniform(0.6, 0.9)
            v = random.uniform(0.8, 0.95)
        elif style == "NoiseTouch":
            s = random.uniform(0.4, 0.7)
            v = random.uniform(0.8, 0.95)
        else:
            s, v = 0.5, 0.9

        r, g, b = hsv_to_rgb(h, s, v)
        palette.append((r, g, b))
    return palette


# -------------------------------
# 🌀 2. Blob generator
# -------------------------------
def generate_blob(center=(0, 0), radius=1.5, wobble=0.2, points=150):
    """Create a set of (x, y) coordinates for an irregular circular blob."""
    angles = np.linspace(0, 2*np.pi, points)
    r = radius * (1 + wobble * (np.random.rand(points) - 0.5) * 2)
    x = center[0] + r * np.cos(angles)
    y = center[1] + r * np.sin(angles)
    return x, y


# -------------------------------
# 🧩 3. Drawing function
# -------------------------------
def draw_poster(n_blobs, blob_radius_range, wobble_range, style, seed):
    """Generate a generative abstract poster."""
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)

    palette = generate_palette(style, n_colors=n_blobs, seed=seed)

    fig, ax = plt.subplots(figsize=(7, 7))
    ax.set_aspect('equal')
    ax.axis('off')
    ax.set_xlim(-10, 10)
    ax.set_ylim(-10, 10)
    ax.set_facecolor((0.98, 0.98, 0.97))

    for i in range(n_blobs):
        radius = random.uniform(*blob_radius_range)
        wobble = random.uniform(*wobble_range)
        if style == "NoiseTouch":
            wobble *= 1.5
        center = (random.uniform(-9, 9), random.uniform(-9, 9))
        x, y = generate_blob(center, radius, wobble)
        ax.fill(
            x, y,
            color=palette[i % len(palette)],
            alpha=random.uniform(0.25, 0.55)
        )

    ax.text(0.95, 0.95, "Made by He Pengwei", fontsize=12,
            ha='right', va='top', transform=ax.transAxes)
    ax.text(0.95, 0.91, "Arts & Advanced Big Data Week3", fontsize=12,
            ha='right', va='top', transform=ax.transAxes)

    st.pyplot(fig)


# -------------------------------
# 🌐 4. Streamlit Web Interface
# -------------------------------
st.set_page_config(page_title="Generative Poster by He Pengwei", layout="centered")
st.title("🎨 Generative Abstract Poster (Week 3)")
st.markdown("Create unique, data-driven abstract art using random generative blobs.")

# Sidebar Controls
st.sidebar.header("Adjust Parameters")
style = st.sidebar.selectbox("🎨 Style", ["Minimal", "Vivid", "NoiseTouch"])
n_blobs = st.sidebar.slider("🟣 Number of Blobs", 3, 30, 12)
blob_radius_range = st.sidebar.slider("⚪ Blob Size Range", 1.0, 10.0, (3.0, 5.0))
wobble_range = st.sidebar.slider("🌊 Wobble Range", 0.0, 0.5, (0.05, 0.2))
seed = st.sidebar.number_input("🔢 Random Seed (for repeatable results)", value=0, min_value=0, max_value=9999)

# Button to generate
if st.button("✨ Generate Poster"):
    draw_poster(n_blobs, blob_radius_range, wobble_range, style, seed)
else:
    st.info("Click the button to generate your poster.")